{{- if not .Values.statefulSet.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Values.rollout.canary.analysis.templateName | default "success-rate" }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  metrics:
    - name: webcheck
      provider:
        web:
          url: http://{{ include "common.fullname" . }}.{{ .Release.Namespace }}.svc/health
          jsonPath: "{$.status}"
      successCondition: result == "healthy"
      interval: 10s
      count: 3
      failureLimit: 1
{{- end }}
